version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: greenhouse_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: greenhouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d greenhouse"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: